import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";
import OpenWeather from '../components/openweather/openWeather'
import {useEffect, useState} from 'react';
import {useRouter} from 'next/router'
import Navigation from '../components/navigation/navigation'
import CreatorCard from "../components/creatorpick/creatorPick";
import { Player } from "@lottiefiles/react-lottie-player";
import AppText from "../components/apptext/apptext";
import LandingCard from "../components/landingcard/landingCard";
import AppButton from "../components/button/button";
import Footer from "../components/footer/footer";
import { useSession } from "next-auth/react";



export const Wrapper = styled.div`
display: flex;
flex-direction: column;
align-items: center;
width:100vw;
`

const Photo = styled(Image)`
opacity: 0.3;
object-fit:contain;

@media (min-width: 701px) and (max-width: 1120px) {
  width: 40%;
}

@media (max-width: 700px) {
  width: 40%;
}

`

const Row = styled.div`
display:flex;
flex-direction:row;
padding: 2em 3em;
align-items:center;
justify-content:space-around;
width:100%;
margin-bottom:5rem;
`

const LandingContainer = styled.div`
display:flex;
flex-direction:row;
align-items:flex-start;
margin:3em 0 2em 0;
width:100%;
justify-content:space-around;
padding: 2em 3em;
`

const Column = styled.div`
display:flex;
flex-direction:column;
width:75%;

@media (min-width: 701px) and (max-width: 1120px) {
  width: 75%;
};

@media (max-width: 700px) {
  width: 80%;
}

`

const LandingText = styled.div`
display:flex;
flex-direction:column;
align-items:flex-start;
width:100%;
`

const AnimCont = styled.div`
width:40rem;
position:absolute;
top:5px;
left:0px;
`

const Block = styled.div`
background-color: ${props => props.background};
border-radius: 2rem;
width:12rem;
height: ${props => props.height};
margin: ${props => props.margin};
box-shadow: rgba(0, 0, 0, 0.3) 2px 2px 2px;
display:flex;
flex-direction:column;  
align-items:flex-start;
justify-content:space-between;
padding: 3rem 2rem;
position:relative;

@media (min-width: 701px) and (max-width: 1120px) {
  width: 9rem;
  height: ${props => props.tabletheight};
  padding: 2rem 1rem;
};

@media (max-width: 700px) {
  width: 6rem;
  height: ${props => props.mobileheight};
  border-radius:1.5rem;
  padding: 1.5rem 1rem;
}

`

const BlockCont = styled.div`
display:flex;
gap:2rem;
@media (max-width: 700px) {
  gap: 0.75rem;
  display:none;
}
`

const LandingBottom = styled.div`
display:flex;
flex-direction:row;
align-items:center;
gap:4rem;

@media (max-width: 700px) {
  gap: 2rem;
}

`

const BottomSection = styled.section`
display:flex;
flex-direction:column;
justify-content:space-evenly;
align-items:center;
width:100%;
background-color:#EDEDE8;
border-radius:4em 4em 0 0;

@media (max-width: 600px) {
  flex-direction: column;
}
`

const BottomCont = styled.div`
display:flex;
flex-direction:column;
gap:5rem;
padding-top:5rem;

@media (min-width: 701px) and (max-width: 1120px) {
  gap:1rem;
};

@media (max-width: 700px) {
  gap:0.5rem;
  padding-top:3rem;
}
`

export default function Home() {


  const router = useRouter()


  useEffect(() => {
   

}, [])



function stylizeLastWord(text, color) {
  const words = text.split(" ");
  const lastWord = words.pop();

  return (
    <>
      {words.join(" ")}
      <AppText c='pink' variant='landing' text={lastWord}></AppText>
    </>
  );

}

  return (
    <>
      <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.svg" />
      </Head>

      <Navigation/>
      <Wrapper>

      <LandingContainer>
        <LandingText>
          <Column>
          <AppText variant='landing' c='black' wdth='100%' text={stylizeLastWord("EXPLORE THE\nWORLD OF\nENDLESS  JAMS", "pink")} align='left' style={{whiteSpace: 'pre-line'}}/>
          <AppText variant='bodySmall' c='gray' wdth='100%' margin='1rem 0 2rem 0 ' text={"Easily find music you never knew you needed. Simply generate a unique mix of songs that you'll love. Get ready to explore new music, find hidden gems, and shape your own unique music experience."}/>
          </Column>
          <AppButton onClick={()=>router.push("/music")} variant='contained' buttonSize='buttonLarge' bg='black' text='DISCOVER' textcolor='sand' textWidth='100%'/>
        </LandingText>
        
        <BlockCont>
          <Block background='#dd727f' height='20rem' mobileheight='11rem' tabletheight='15rem'>
            <AppText variant='headerSmall' c='sand' align='left' wdth='100%' text="Music for Every Mood"/>
            <Player
              autoplay
              loop
              src="animations/spotify.json"
              className={styles.spotify}
              speed={0.5}
            />
          </Block>
          <Block background='#aac5bf' height='27rem' mobileheight='15rem' tabletheight='20.25rem' style={{overflow:'none'}} >
            <AppText variant='headerSmall' c='sand' align='left' wdth='100%' text="Over 1 Billion + Music Available"/>
            <Player 
              autoplay
              loop
              src='animations/music.json'
              speed={0.8}
              className={styles.music}
            />
          </Block>
        </BlockCont>
      </LandingContainer>

      <Row>
      <AppText text='powered by' c='gray' variant='bodySmall' wdth="100%"/>
      <LandingBottom>
        <Photo src='/spotify.png' width={85} height={50}></Photo>
        <Photo src='/openweather.png' width={85} height={50}></Photo>
      </LandingBottom>
      </Row>

      <BottomSection>

        <BottomCont>
        <CreatorCard/>
        <OpenWeather/>
        </BottomCont>

        <Footer/>
      </BottomSection>
      {/* <Column style={{justifyContent:'flex-start'}}>
        <AppText variant='headerSmall' text='Creator&#39;s Picks'></AppText> 
        <CreatorCard/>
      </Column>
       */}


      </Wrapper>
    </>
  );
}
